---
title: "GLM Practical"
author: "Praise Adeyemo"
date: "2024-09-30"
output:
  word_document: default
  html_document: default
---
##################################
# GLM Practical on 'Birds urge to migrate or seasonal restlessness'
# Data collected by Dr Barbara Helm in 2009 - 2010

```{r}
setwd("~/Documents/UofG PhD Masterfile/KRS 2024/GLM/Practical 1") #to set working directory for the practical
stonechats <- read.csv("stonechats.csv") #to import data to be used in the practical
str(stonechats) #to view the features of the imported data
#Data set contains four variables - Animal_ID, hatchdate, noc-age and group
View(stonechats) #to view the data set [since R is case sensitive, the function to view should start with a capital letter, i.e. View() not view()]
```

```{r}
#Interesting questions to explore with the dataset
# (a) Is there a difference between European or African stonechats in the age they first show nocturnal activity?
# (b) Does the age the birds first show nocturnal activity depend on the hatching date of stonechats?


#Model: noc_age~group
#Question 1: Defining the hypotheses
#Null hypothesis (H0): There is no difference between European or African stonechats at noc_age
#Alternative hypothesis (Ha): There is a difference between European or African stonechats at noc_age


#Question 2: Types of data
#Animal_ID is a factor nominal data
#hatchdate is a covariate continuous data
#noc-age is a covariate discrete data
#group is a factor nominal data


#Question 3
#Response variable is age they show nocturnal activity (noc_age)


#Question 4
#Explanatory variables are 1) the group of birds - if they are European or African and 2) their hatch date

#Plotting data to see how the group of birds affects the noc_age

library(ggplot2) #to call the package ggplot
ggplot(data = stonechats, aes(x=group, y=noc_age)) +
  geom_boxplot()

#Question 5
#From the graph, the mean noc_age for the European stonechats is 150, while that of the African stonechats is about 120. From the dataset, there are more data points for the European stonechats compared to the African group. The graph also shows this as the lower limit of the African group is within the lower limit of the European group. 'Group' as a variable does not really explain the nocturnal activity of the stonechats

#To statistically test relationship between group and noc_age by fitting a categorical GLM to the data
Model1<-lm(noc_age~group, data=stonechats) #to fit a GLM to the data. Recall that 'response variable' in the model formula is written on the left side of the ~ and the explanatory variable(s) is written on the right side of the ~
anova(Model1) #to explore the output of the GLM showing the sums of squares, mean square, p-value


#Question 6
#Explained sum of squares (ESS) is 2774 and residuals sum of squares (RSS) is 41854 
ESS = 2774
RSS = 41854
TSS = ESS + RSS #to calculate the total sums of squares 
2774 + 41854 # manually calculating the total sums of squares 
TSS
#44628 is the total sums of squares
#ESS is lower than RSS, showing a wide variation 

TSS <- ((stonechats$noc_age - mean(stonechats$noc_age))^2) #to manually calculate the total sums of squares (TSS)
TSS #to see the value of TSS
sum(TSS) #to sum TSS and compare with sums of squares for the group and Residuals
#sum(TSS) = 44627.69, which is similar to the sums of squares for the group and residuals

RSS<-sum((Model1$fitted - stonechats$noc_age)^2) #to manually calculate the residual sums of squares
RSS #to see the value of RSS
#RSS is 41853.93 which is similar to the anova output (41854)


#Question 7
#Percentage of variation explained by the model (R-squared)
ESS <- TSS-RSS #where ESS is explained sum of squares, TSS is total sum of squares and RSS is residuals sum of squares
ESS
#ESS is 2774

Rsquared <- (ESS/TSS) #to calculate R-squared, the amount of variation explained as a proportion of the total variation 
Rsquared
Rsquared*100 #to express this as a percentage
#R-squared is 0.06215829 or 6.215829 or 6.22%

summary(Model1) #to find out the average age of nocturnal activity predicted by the model and how big the difference is between European and African birds


#Question 8
#p-value in the anova output is 9.13e-15 ***, so we reject the null hypothesis that there is no difference between European or African stonechats at noc_age


#Question 9
#This is not a good model. The multiple R-squared's value (0.06215) means that the group of stonechats (African or European) explains only ~6.22% of the variation in nocturnal activity.

```


```{r}

#(b) Does the age the birds first show nocturnal activity depend on the hatching date of stonechats?

#Model 2: noc_age~hatchdate

#Question 1: Defining the hypotheses
#Null hypothesis (H0): Hatching date of stonechats does not effect age the birds show nocturnal activity
#Alternative hypothesis (Ha): Hatching date of stonechats effects age the birds show nocturnal activity


#Question 2
#Response variable is age they show nocturnal activity (noc_age) while explanatory variable is the hatching date


#Question 3
#Plotting data to see how the hatching date affects the noc_age. We will use a scattered plot because the explanatory variable (hatching date) is a covariate
library(ggplot2) #to call the package ggplot
ggplot(data = stonechats, aes(x=hatchdate, y=noc_age)) +
  geom_point() #prompt for scattered plot
#From the scattered plot, there is a downward relationship between the age that they start nocturnal activities and the hatching date, i.e. stonechats that hatch later (around day 200) develop nocturnal activity relatively earlier (around days 100 - 125). Another way to describe this is to say that the older the hatching date, the earlier the commencement of nocturnal activity. It's interesting to see that a stonechat with a hatching date of ~173 days attained nocturnal activity earliest at day day 50


#Question 4
#To statistically test relationship between hatching date and noc_age by fitting a categorical GLM to the data
Model2<-lm(noc_age~hatchdate, data=stonechats) #to fit a GLM to the data
anova(Model2) #to explore the output of the GLM showing the sums of squares, mean square, p-value


#Question 6
#Explained sum of squares (ESS) is 30642 and residuals sum of squares (RSS) is 13986 
ESS = 30642 #the amount of variation explained by the "hatchdate" variable
RSS = 13986 #the amount of variation in the response variable that was not explained by the model
#ESS is higher than the RSS, showing that hatchdate explains the response variable - the age at which the stonechats develop nocturnal activity
TSS = ESS + RSS #to calculate the total sums of squares 
TSS
#44628 is the total sums of squares


TSS <- ((stonechats$noc_age - mean(stonechats$noc_age))^2) #to manually calculate the total sums of squares (TSS)
TSS #to see the value of TSS
sum(TSS) #to sum TSS and compare with sums of squares for the group and Residuals
#sum(TSS) = 44627.69, which is similar to the sums of squares for the explanatory variable and residual

RSS<-sum((Model2$fitted - stonechats$noc_age)^2) #to manually calculate the residual sums of squares
RSS #to see the value of RSS
#RSS is 13986.05 which is similar to the anova output for RSS (13986)
ESS <- TSS-RSS #where ESS is explained sum of squares, TSS is total sum of squares and RSS is residuals sum of squares
ESS <- 44627.69-13986.05
ESS #ESS is 30641.64

Rsquared <- ESS/TSS #to calculate R-squared, the amount of variation explained as a proportion of the total variation 
Rsquared
Rsquared*100 #to express this as a percentage
#R-squared is 0.686606 or or 68.66%

summary(Model2) 


#Question 7
#p-value in the anova output is < 2e-16 ***, so we fail to reject the null hypothesis that hatching date of stonechats does not effect age the birds show nocturnal activity. This is  a good model. The multiple R-square's value (0.68) means that hatching date explains the variation in nocturnal activity by a high percentage - 68%.

```

