---
title: "Advanced R_Chapter 5"
author: Praise Adeyemo
date:   15th October 2024
output: html_notebook

editor_options: 
  chunk_output_type: inline
---


```{r}
setwd("~/Documents/UofG PhD Masterfile/KRS 2024/Intro_to_R/Day 4")
rm(list = ls()) #to clear R's brain

#5.4 Introducing linear models
#General linear models are a class of model that includes regression, multiple regression, ANOVA and ANCOVA
#There is a difference between general linear model and generalized linear model, aka GLM

#5.2
#Points to note when working with data:
#1. Always plot your data first
#2. Understand the hypothesis you are testing, biologically and statistically
#Chi-square contingency table is an analysis of count data, used to test the association among two or more categorical variables

#libraries for this session
library(readr)
library(dplyr)
library(ggplot2)

ladybirds <- read_csv("~/Documents/UofG PhD Masterfile/KRS 2024/Intro_to_R/Data sets/ladybirds_morph_colour.csv")
glimpse(ladybirds) 

#Chi-square contingency analysis
#to test the association between between colours of the lady birds and the habitat, i.e. to test if the frequencies of the two colours of ladybirds diﬀer between the two habitat types

#Defining hypotheses
#H0: there is no association between the colours of the ladybirds and their habitat
#Ha: there is an association between the colours of the ladybirds and their habitat

#5.2.2. Organizing data for plotting and analysis
#to summarise the data by habitat and morph colour
totals <- ladybirds %>% 
    group_by(Habitat, morph_colour) %>%
    summarise(total.number = sum(number)) #total.number is the new column heading for the frequencies of the birds grouped by habitat and colour
View(totals) #dataframe for summary is now called 'totals'
totals

#using barchart to summarize data
ggplot(totals, aes(x = Habitat, y = total.number,
    fill = morph_colour)) +
geom_bar(stat = 'identity', position = 'dodge')
# the aesthetic 'fill = morph_colour' was used here because we want to see our geometry output as a bar, and these bars can be filled with a colour. Using 'colour = morph_colour' will alter the outlines of the bar, so not advisable to use that aesthetic
#stat = 'identity' tells ggplot not to make any calculations
#position = 'dodge' helped us to have the two bars for habitat group next to each other; if we didn't specify that, we would have a stacked barplot


#trying out what will happen without including the aes position
ggplot(totals, aes(x = Habitat, y = total.number,
    fill = morph_colour)) +
geom_bar(stat = 'identity')
#output: a stacked barchart!!


#5.2.4 - Fixing the colours
#we want to ensure that the colours in the barchart are actually black and red as indicated in the data itself

ggplot(totals, aes(x = Habitat, y = total.number,
    fill = morph_colour)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c(black = "black", red = "red"))

#5.2.5 - from the graph, we see that there are more black ladybirds in the industrial havitat vs the rural habitat that has more red ladybirds
#Important note here: We ahevn't used the Chi-square here. Recall, the chi-square test compares the frequencies/proportion and not absolute numbers 


#5.2.6
#to run the chi-square, you need to present your data as a matrix; this means transforming your dataframe into a matrix
#to do this, we will use the xtabs() function, which is the equivalent of a cross(x)-tabulation in Excel

ladybirds.mat <- xtabs(number ~ Habitat + morph_colour,
data = ladybirds)
#Please cross-tabulate the 'number' column of counts in the totals dataframe by the Habitat and morph_colour variables
#ladybirds.mat is the new name we're calling the matrix data, number here is a column header in the original data (ladybirds)
ladybirds.mat


chisq.test(ladybirds.mat) #to run the chi-square to test the association between the ladybirds habitats and colour
#chi-square test shows that there is some association between the habitats and the colour. The p-value (0.00001239) which is less than 0.005 means that we will reject the null hypothesis
#In a manuscript, we'll report this result as χ2 = 19.1, df = 1, p < 0.001, with black morphs more frequent in the industrial habitats and the red birds in the rural habitats


#Yates' continuity is a little adjustment made to the χ2 test to make it a bit more reliable when the counts are small
#to view the conventional χ2 test result, see below
ladybirds.chi <- chisq.test(ladybirds.mat) #we assign a new name to our test, i.e. ladybirds.chi
names(ladybirds.chi)
ladybirds.chi$expected
ladybirds.chi$p.value
#p.value = 1.238571e-05

ladybirds.chi$method

```

```{r}
#5.3 - Two-sample t-test
#This test is a comparison of the means of two groups of numeric values
#Appropriate when the sample sizes in each group are small
#It also asssumes that the data in each group are normally distributed and that their variances are equal

rm(list = ls()) #to clear R's brain
setwd("~/Documents/UofG PhD Masterfile/KRS 2024/Intro_to_R/Day 4")

#libraries for this session
library(readr)
library(dplyr)
library(ggplot2)

GardenOzone <- read.csv("~/Documents/UofG PhD Masterfile/KRS 2024/Intro_to_R/Data sets/GardenOzone.csv")
View(GardenOzone)
glimpse(GardenOzone)

#Plotting the data
#Since there are only two groups in the factor data - Garden Location, and we are interested in comparing ozone levels between the 2 regions, a good tool for plotting the data is an histogram

ggplot(GardenOzone, aes(x = Ozone)) +
    geom_histogram(binwidth = 10) +
    facet_wrap(~ Garden.location, ncol = 1) +
    theme_bw()
library(dplyr) 
t.test(Ozone ~ Garden.location, data = GardenOzone)
#If the difference between two things is 0, then they are the same. In this case, the sample t-test shows that the difference between the means of the East and West groups is not equal to 0

var.test(Ozone ~ Garden.location, data = GardenOzone)
#to test for equality of variance in a two-sample t-test

```

```{r}
#5.5.Simple linear regression
rm(list = ls())

setwd("~/Documents/UofG PhD Masterfile/KRS 2024/Intro_to_R/Day 4")

#libraries for this session
library(readr)
library(dplyr)
library(ggplot2)

Plant_GR <- read.csv("~/Documents/UofG PhD Masterfile/KRS 2024/Intro_to_R/Data sets/plant.growth.rate.csv")
glimpse(Plant_GR)

View(Plant_GR)

#Plotting the data
ggplot(Plant_GR,
      aes(x = soil.moisture.content, y = plant.growth.rate)) +
      geom_point() +
      ylab("Plant Growth Rate (mm/week)") +
      theme_bw()
#ylab - mm/week has been added as the unit for the y axis
#theme for the plot is black and white
#Scatter plot shows a positive relationship between growth rate of plans and the moisture content of the soil. More moisture content leads to higher growth rate 

#With the plot, growth rate is roughly between 20 and 50, moisture content between 0 and 2. Gradient is ~ 30/2 = 15 (change in y axis/change in x axis). Intercept (where x = 0 on the y-axis)

#Simple linear regression
model_pgr <- lm(plant.growth.rate ~ soil.moisture.content,
data = Plant_GR)
#Fit a linear model,where we hypothesize that plant growth rate is a function of soil moisture content, using the variables from the Plant_GR dataframe
model_pgr

#using anova does not mean you are performing an ANOVA that compares means
#anova in R produces a classic table in statistics, the sums of squares
anova(model_pgr)
#it's interesting to see that the residuals explaining plant growth rate are more than the explanatory variable soil moisture content

install.packages("ggfortify")
library(ggfortify)  #package to check the assumptions of a linear model
autoplot(model_pgr, smooth.colour = NA)





```


