###############################################################################
# Intro to R Class - Day 2 #
# Friday, 27th September, 2024#
###############################################################################
# Learning R from scratch using the R Beginners' Textbook by Beckerman et al (2017) #
# Script for Chapter 2 #
###############################################################################
# Created by P.A. on 27/09/2024, last modified on xx/09/2024 #
###############################################################################

# Getting started with importing data in preparation for data analysis
library(readr)
compensation <- read.csv("Documents/UofG PhD Masterfile/KRS 2024/Intro_to_R/Data sets/compensation.csv") #to find path containing data file
View(compensation) #to view data


# Alternative
file.choose() #manual selection of file from Macbook
"/Users/praiz1/Documents/UofG PhD Masterfile/KRS 2024/Intro_to_R/Data sets/compensation.csv" #copied from Console and pasted here
compensation <- read.csv("/Users/praiz1/Documents/UofG PhD Masterfile/KRS 2024/Intro_to_R/Data sets/compensation.csv") #code for R to read the data file. <- was used to import the data into an "object" and in this case, "compensation" is the object

# What if I don't want to use a file path because things can change?!
# I will go ahead to set a working directory: 
# To do this, I'll go to the Session option on the tool bar in R -> click on Set Working Directory -> select Choose Directory. This will point RStudio's eyes at a folder in a specific location
# So I can just go ahead to specify the file name I want to access as long as it is in the specific working directory. I'll do this by: see line 25 below 
read.csv("compensation.csv") #the advantage of this is that I don't need to update my file paths if I move folders!

# Confirming the data
names (compensation) # to check the variable names or column headings
head (compensation)




